apiVersion: v1
kind: Service
metadata:
  labels:
    app: hktv-ars-backend
  name: hktv-ars-backend-svc
  namespace: hktv-ars
spec:
  ports:
    - name: hktv-ars-backend-80-8090
      port: 80
      targetPort: 8090
  selector:
    app: hktv-ars-backend
  type: ClusterIP