use hktv_ars;

CREATE TABLE IF NOT EXISTS `QRTZ_JOB_DETAILS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `JOB_NAME` VARCHAR(190) NOT NULL,
    `JOB_GROUP` VARCHAR(190) NOT NULL,
    `DESCRIPTION` VARCHAR(250) NULL DEFAULT NULL,
    `JOB_CLASS_NAME` VARCHAR(250) NOT NULL,
    `IS_DURABLE` VARCHAR(1) NOT NULL,
    `IS_NONCONCURRENT` VARCHAR(1) NOT NULL,
    `IS_UPDATE_DATA` VARCHAR(1) NOT NULL,
    `REQUESTS_RECOVERY` VARCHAR(1) NOT NULL,
    `JOB_DATA` BLOB NULL DEFAULT NULL,
    PRIMARY KEY (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`),
    INDEX `IDX_QRTZ_J_REQ_RECOVERY` (`SCHED_NAME` ASC, `REQUESTS_RECOVERY` ASC) VISIBLE,
    INDEX `IDX_QRTZ_J_GRP` (`SCHED_NAME` ASC, `JOB_GROUP` ASC) VISIBLE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS `QRTZ_TRIGGERS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `TRIGGER_NAME` VARCHAR(190) NOT NULL,
    `TRIGGER_GROUP` VARCHAR(190) NOT NULL,
    `JOB_NAME` VARCHAR(190) NOT NULL,
    `JOB_GROUP` VARCHAR(190) NOT NULL,
    `DESCRIPTION` VARCHAR(250) NULL DEFAULT NULL,
    `NEXT_FIRE_TIME` BIGINT NULL DEFAULT NULL,
    `PREV_FIRE_TIME` BIGINT NULL DEFAULT NULL,
    `PRIORITY` INT NULL DEFAULT NULL,
    `TRIGGER_STATE` VARCHAR(16) NOT NULL,
    `TRIGGER_TYPE` VARCHAR(8) NOT NULL,
    `START_TIME` BIGINT NOT NULL,
    `END_TIME` BIGINT NULL DEFAULT NULL,
    `CALENDAR_NAME` VARCHAR(190) NULL DEFAULT NULL,
    `MISFIRE_INSTR` SMALLINT NULL DEFAULT NULL,
    `JOB_DATA` BLOB NULL DEFAULT NULL,
    PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
    INDEX `IDX_QRTZ_T_J` (`SCHED_NAME` ASC, `JOB_NAME` ASC, `JOB_GROUP` ASC) VISIBLE,
    INDEX `IDX_QRTZ_T_JG` (`SCHED_NAME` ASC, `JOB_GROUP` ASC) VISIBLE,
    INDEX `IDX_QRTZ_T_C` (`SCHED_NAME` ASC, `CALENDAR_NAME` ASC) VISIBLE,
    INDEX `IDX_QRTZ_T_G` (`SCHED_NAME` ASC, `TRIGGER_GROUP` ASC) VISIBLE,
    INDEX `IDX_QRTZ_T_STATE` (`SCHED_NAME` ASC, `TRIGGER_STATE` ASC) VISIBLE,
    INDEX `IDX_QRTZ_T_N_STATE` (`SCHED_NAME` ASC, `TRIGGER_NAME` ASC, `TRIGGER_GROUP` ASC, `TRIGGER_STATE` ASC) VISIBLE,
    INDEX `IDX_QRTZ_T_N_G_STATE` (`SCHED_NAME` ASC, `TRIGGER_GROUP` ASC, `TRIGGER_STATE` ASC) VISIBLE,
    INDEX `IDX_QRTZ_T_NEXT_FIRE_TIME` (`SCHED_NAME` ASC, `NEXT_FIRE_TIME` ASC) VISIBLE,
    INDEX `IDX_QRTZ_T_NFT_ST` (`SCHED_NAME` ASC, `TRIGGER_STATE` ASC, `NEXT_FIRE_TIME` ASC) VISIBLE,
    INDEX `IDX_QRTZ_T_NFT_MISFIRE` (`SCHED_NAME` ASC, `MISFIRE_INSTR` ASC, `NEXT_FIRE_TIME` ASC) VISIBLE,
    INDEX `IDX_QRTZ_T_NFT_ST_MISFIRE` (`SCHED_NAME` ASC, `MISFIRE_INSTR` ASC, `NEXT_FIRE_TIME` ASC, `TRIGGER_STATE` ASC) VISIBLE,
    INDEX `IDX_QRTZ_T_NFT_ST_MISFIRE_GRP` (`SCHED_NAME` ASC, `MISFIRE_INSTR` ASC, `NEXT_FIRE_TIME` ASC, `TRIGGER_GROUP` ASC, `TRIGGER_STATE` ASC) VISIBLE,
    CONSTRAINT `qrtz_triggers_ibfk_1`
    FOREIGN KEY (`SCHED_NAME` , `JOB_NAME` , `JOB_GROUP`)
    REFERENCES `QRTZ_JOB_DETAILS` (`SCHED_NAME` , `JOB_NAME` , `JOB_GROUP`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS `QRTZ_BLOB_TRIGGERS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `TRIGGER_NAME` VARCHAR(190) NOT NULL,
    `TRIGGER_GROUP` VARCHAR(190) NOT NULL,
    `BLOB_DATA` BLOB NULL DEFAULT NULL,
    PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
    INDEX `SCHED_NAME` (`SCHED_NAME` ASC, `TRIGGER_NAME` ASC, `TRIGGER_GROUP` ASC) VISIBLE,
    CONSTRAINT `qrtz_blob_triggers_ibfk_1`
    FOREIGN KEY (`SCHED_NAME` , `TRIGGER_NAME` , `TRIGGER_GROUP`)
    REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME` , `TRIGGER_NAME` , `TRIGGER_GROUP`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `QRTZ_CALENDARS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `CALENDAR_NAME` VARCHAR(190) NOT NULL,
    `CALENDAR` BLOB NOT NULL,
    PRIMARY KEY (`SCHED_NAME`, `CALENDAR_NAME`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `QRTZ_CRON_TRIGGERS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `TRIGGER_NAME` VARCHAR(190) NOT NULL,
    `TRIGGER_GROUP` VARCHAR(190) NOT NULL,
    `CRON_EXPRESSION` VARCHAR(120) NOT NULL,
    `TIME_ZONE_ID` VARCHAR(80) NULL DEFAULT NULL,
    PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
    CONSTRAINT `qrtz_cron_triggers_ibfk_1`
    FOREIGN KEY (`SCHED_NAME` , `TRIGGER_NAME` , `TRIGGER_GROUP`)
    REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME` , `TRIGGER_NAME` , `TRIGGER_GROUP`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `QRTZ_FIRED_TRIGGERS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `ENTRY_ID` VARCHAR(95) NOT NULL,
    `TRIGGER_NAME` VARCHAR(190) NOT NULL,
    `TRIGGER_GROUP` VARCHAR(190) NOT NULL,
    `INSTANCE_NAME` VARCHAR(190) NOT NULL,
    `FIRED_TIME` BIGINT NOT NULL,
    `SCHED_TIME` BIGINT NOT NULL,
    `PRIORITY` INT NOT NULL,
    `STATE` VARCHAR(16) NOT NULL,
    `JOB_NAME` VARCHAR(190) NULL DEFAULT NULL,
    `JOB_GROUP` VARCHAR(190) NULL DEFAULT NULL,
    `IS_NONCONCURRENT` VARCHAR(1) NULL DEFAULT NULL,
    `REQUESTS_RECOVERY` VARCHAR(1) NULL DEFAULT NULL,
    PRIMARY KEY (`SCHED_NAME`, `ENTRY_ID`),
    INDEX `IDX_QRTZ_FT_TRIG_INST_NAME` (`SCHED_NAME` ASC, `INSTANCE_NAME` ASC) VISIBLE,
    INDEX `IDX_QRTZ_FT_INST_JOB_REQ_RCVRY` (`SCHED_NAME` ASC, `INSTANCE_NAME` ASC, `REQUESTS_RECOVERY` ASC) VISIBLE,
    INDEX `IDX_QRTZ_FT_J_G` (`SCHED_NAME` ASC, `JOB_NAME` ASC, `JOB_GROUP` ASC) VISIBLE,
    INDEX `IDX_QRTZ_FT_JG` (`SCHED_NAME` ASC, `JOB_GROUP` ASC) VISIBLE,
    INDEX `IDX_QRTZ_FT_T_G` (`SCHED_NAME` ASC, `TRIGGER_NAME` ASC, `TRIGGER_GROUP` ASC) VISIBLE,
    INDEX `IDX_QRTZ_FT_TG` (`SCHED_NAME` ASC, `TRIGGER_GROUP` ASC) VISIBLE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `QRTZ_LOCKS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `LOCK_NAME` VARCHAR(40) NOT NULL,
    PRIMARY KEY (`SCHED_NAME`, `LOCK_NAME`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `QRTZ_PAUSED_TRIGGER_GRPS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `TRIGGER_GROUP` VARCHAR(190) NOT NULL,
    PRIMARY KEY (`SCHED_NAME`, `TRIGGER_GROUP`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `QRTZ_SCHEDULER_STATE` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `INSTANCE_NAME` VARCHAR(190) NOT NULL,
    `LAST_CHECKIN_TIME` BIGINT NOT NULL,
    `CHECKIN_INTERVAL` BIGINT NOT NULL,
    PRIMARY KEY (`SCHED_NAME`, `INSTANCE_NAME`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `QRTZ_SIMPLE_TRIGGERS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `TRIGGER_NAME` VARCHAR(190) NOT NULL,
    `TRIGGER_GROUP` VARCHAR(190) NOT NULL,
    `REPEAT_COUNT` BIGINT NOT NULL,
    `REPEAT_INTERVAL` BIGINT NOT NULL,
    `TIMES_TRIGGERED` BIGINT NOT NULL,
    PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
    CONSTRAINT `qrtz_simple_triggers_ibfk_1`
    FOREIGN KEY (`SCHED_NAME` , `TRIGGER_NAME` , `TRIGGER_GROUP`)
    REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME` , `TRIGGER_NAME` , `TRIGGER_GROUP`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `QRTZ_SIMPROP_TRIGGERS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `TRIGGER_NAME` VARCHAR(190) NOT NULL,
    `TRIGGER_GROUP` VARCHAR(190) NOT NULL,
    `STR_PROP_1` VARCHAR(512) NULL DEFAULT NULL,
    `STR_PROP_2` VARCHAR(512) NULL DEFAULT NULL,
    `STR_PROP_3` VARCHAR(512) NULL DEFAULT NULL,
    `INT_PROP_1` INT NULL DEFAULT NULL,
    `INT_PROP_2` INT NULL DEFAULT NULL,
    `LONG_PROP_1` BIGINT NULL DEFAULT NULL,
    `LONG_PROP_2` BIGINT NULL DEFAULT NULL,
    `DEC_PROP_1` DECIMAL(13,4) NULL DEFAULT NULL,
    `DEC_PROP_2` DECIMAL(13,4) NULL DEFAULT NULL,
    `BOOL_PROP_1` VARCHAR(1) NULL DEFAULT NULL,
    `BOOL_PROP_2` VARCHAR(1) NULL DEFAULT NULL,
    PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
    CONSTRAINT `qrtz_simprop_triggers_ibfk_1`
    FOREIGN KEY (`SCHED_NAME` , `TRIGGER_NAME` , `TRIGGER_GROUP`)
    REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME` , `TRIGGER_NAME` , `TRIGGER_GROUP`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;